services:
  db_postgres:
    image: postgres:18-alpine
    container_name: postgres_18_local
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
      
  storecore.webapp:
    image: ${DOCKER_REGISTRY-}storecorewebapp
    user: "root"
    build:
      context: .
      dockerfile: StoreCore.WebApp/StoreCore.WebApp/Dockerfile
    depends_on:
      - db_postgres 
    environment:
      - ConnectionStrings__DefaultConnection=${DB_CONNECTION_STRING}
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8080:8080"
    volumes:
      - user_images:/app/wwwroot/uploads
      - app_keys:/app/dpkeys

volumes:
  pg_data:      
  user_images: 
  app_keys: